/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.*;
import classesApp.Motivo;
import java.util.List;
import java.awt.event.*;

/**
 *
 * @author GASS
 */
public class Menu_PCR extends javax.swing.JFrame {

    /**
     * Creates new form Menu_PCR
     */
    private String Valor_motivo_pcr;

    
    public Menu_PCR() {
        
        Motivo_box = new JComboBox<>();
        initComponents();
        setupComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jDesktopPanePCR1 = new javax.swing.JDesktopPane();
        Label_Motivo_PCR1 = new javax.swing.JLabel();
        Label_Equipa_Local_SAV1 = new javax.swing.JLabel();
        Labe_EEMI_SAV = new javax.swing.JLabel();
        Motivo_box = new javax.swing.JComboBox<>();
        Equipa_Local_SAV = new javax.swing.JComboBox<>();
        PCR_Voltar = new javax.swing.JButton();
        Equipa_Local_SAV1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        n_evento = new javax.swing.JLabel();
        PCR_Voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jDesktopPanePCR1.setBackground(new java.awt.Color(242, 242, 242));
        jDesktopPanePCR1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PCR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        jDesktopPanePCR1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        Label_Motivo_PCR1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Label_Motivo_PCR1.setText("Motivo PCR");

        Label_Equipa_Local_SAV1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Label_Equipa_Local_SAV1.setText("Equipa Local faz SAV");

        Labe_EEMI_SAV.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Labe_EEMI_SAV.setText("EEMI realiza SAV?");

        Motivo_box.setBackground(new java.awt.Color(242, 242, 242));
        Motivo_box.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Motivo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motivo_boxActionPerformed(evt);
            }
        });

        Equipa_Local_SAV.setBackground(new java.awt.Color(242, 242, 242));
        Equipa_Local_SAV.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Equipa_Local_SAV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Sim", "0 - Nao", " " }));
        Equipa_Local_SAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipa_Local_SAVActionPerformed(evt);
            }
        });

        PCR_Voltar.setBackground(new java.awt.Color(242, 242, 242));
        PCR_Voltar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PCR_Voltar.setText("Voltar");
        PCR_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCR_VoltarActionPerformed(evt);
            }
        });

        Equipa_Local_SAV1.setBackground(new java.awt.Color(242, 242, 242));
        Equipa_Local_SAV1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Equipa_Local_SAV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Sim", "0 - Nao", " " }));
        Equipa_Local_SAV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipa_Local_SAV1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Evento: ");

        n_evento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PCR_Voltar1.setBackground(new java.awt.Color(242, 242, 242));
        PCR_Voltar1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PCR_Voltar1.setText("Seguinte");
        PCR_Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCR_Voltar1ActionPerformed(evt);
            }
        });

        jDesktopPanePCR1.setLayer(Label_Motivo_PCR1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Label_Equipa_Local_SAV1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Labe_EEMI_SAV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Motivo_box, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Equipa_Local_SAV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(PCR_Voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Equipa_Local_SAV1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(n_evento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(PCR_Voltar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePCR1Layout = new javax.swing.GroupLayout(jDesktopPanePCR1);
        jDesktopPanePCR1.setLayout(jDesktopPanePCR1Layout);
        jDesktopPanePCR1Layout.setHorizontalGroup(
            jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePCR1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PCR_Voltar1)
                        .addGap(18, 18, 18)
                        .addComponent(PCR_Voltar))
                    .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                        .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Label_Motivo_PCR1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_Equipa_Local_SAV1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Motivo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Equipa_Local_SAV, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(n_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                                    .addComponent(Labe_EEMI_SAV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Equipa_Local_SAV1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 88, Short.MAX_VALUE))))
        );
        jDesktopPanePCR1Layout.setVerticalGroup(
            jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(n_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Motivo_PCR1)
                    .addComponent(Motivo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Equipa_Local_SAV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Equipa_Local_SAV1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labe_EEMI_SAV)
                    .addComponent(Equipa_Local_SAV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCR_Voltar)
                    .addComponent(PCR_Voltar1))
                .addContainerGap())
        );

        Motivo_box.getAccessibleContext().setAccessibleName("Motivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPanePCR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPanePCR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Equipa_Local_SAV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipa_Local_SAV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Equipa_Local_SAV1ActionPerformed

    private void PCR_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCR_VoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_PCR_VoltarActionPerformed

    private void Equipa_Local_SAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipa_Local_SAVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Equipa_Local_SAVActionPerformed

    private void Motivo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motivo_boxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Motivo_boxActionPerformed

    private void PCR_Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCR_Voltar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCR_Voltar1ActionPerformed

    private void setupComboBox() {
        Motivo_box.addItem("-");
    
        List<Motivo> motivos = Motivo.getAllMotivos();
        for (Motivo motivo : motivos) {
            Motivo_box.addItem(motivo.getMOTIVO());
        }
    }
    
    private void setupOptions() {
     
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_PCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_PCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_PCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_PCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_PCR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Equipa_Local_SAV;
    private javax.swing.JComboBox<String> Equipa_Local_SAV1;
    private javax.swing.JLabel Labe_EEMI_SAV;
    private javax.swing.JLabel Label_Equipa_Local_SAV1;
    private javax.swing.JLabel Label_Motivo_PCR1;
    private javax.swing.JComboBox<String> Motivo_box;
    private javax.swing.JButton PCR_Voltar;
    private javax.swing.JButton PCR_Voltar1;
    private javax.swing.JDesktopPane jDesktopPanePCR1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel n_evento;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
