/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.*;
import classesApp.Motivo_EEMI_SAV_NAO;
import java.util.List;

/**
 *
 * @author GASS
 */
public class Menu_EEMI_SAV_NAO extends javax.swing.JFrame {

    /**
     * Creates new form Menu_EEMI_SAV_NAO
     */
    public Menu_EEMI_SAV_NAO() {
        
        Motivo_EEMI_SAV_NAO_Box = new JComboBox<>();
        
        initComponents();
        setupComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDesktopPanePCR1 = new javax.swing.JDesktopPane();
        Label_Motivo_Nao_SAV = new javax.swing.JLabel();
        Label_SAV_Nao_Gravar = new javax.swing.JLabel();
        SAV_Nao_Gravar_S = new javax.swing.JButton();
        SAV_Nao_Gravar_Nao = new javax.swing.JButton();
        Motivo_EEMI_SAV_NAO_Box = new javax.swing.JComboBox<>();
        EEMI_SAV_NAO_VOLTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jDesktopPanePCR1.setBackground(new java.awt.Color(242, 242, 242));
        jDesktopPanePCR1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EEMI SAV Não", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        jDesktopPanePCR1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        Label_Motivo_Nao_SAV.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Label_Motivo_Nao_SAV.setText("Motivo de nao SAV");

        Label_SAV_Nao_Gravar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Label_SAV_Nao_Gravar.setText("Gravar");

        SAV_Nao_Gravar_S.setBackground(new java.awt.Color(242, 242, 242));
        SAV_Nao_Gravar_S.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SAV_Nao_Gravar_S.setText("Sim");
        SAV_Nao_Gravar_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAV_Nao_Gravar_SActionPerformed(evt);
            }
        });

        SAV_Nao_Gravar_Nao.setBackground(new java.awt.Color(242, 242, 242));
        SAV_Nao_Gravar_Nao.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SAV_Nao_Gravar_Nao.setText("Nao");
        SAV_Nao_Gravar_Nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAV_Nao_Gravar_NaoActionPerformed(evt);
            }
        });

        Motivo_EEMI_SAV_NAO_Box.setBackground(new java.awt.Color(242, 242, 242));
        Motivo_EEMI_SAV_NAO_Box.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Motivo_EEMI_SAV_NAO_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motivo_EEMI_SAV_NAO_BoxActionPerformed(evt);
            }
        });

        EEMI_SAV_NAO_VOLTAR.setBackground(new java.awt.Color(242, 242, 242));
        EEMI_SAV_NAO_VOLTAR.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        EEMI_SAV_NAO_VOLTAR.setText("Voltar");
        EEMI_SAV_NAO_VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EEMI_SAV_NAO_VOLTARActionPerformed(evt);
            }
        });

        jDesktopPanePCR1.setLayer(Label_Motivo_Nao_SAV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Label_SAV_Nao_Gravar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(SAV_Nao_Gravar_S, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(SAV_Nao_Gravar_Nao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(Motivo_EEMI_SAV_NAO_Box, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePCR1.setLayer(EEMI_SAV_NAO_VOLTAR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePCR1Layout = new javax.swing.GroupLayout(jDesktopPanePCR1);
        jDesktopPanePCR1.setLayout(jDesktopPanePCR1Layout);
        jDesktopPanePCR1Layout.setHorizontalGroup(
            jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                            .addComponent(Label_Motivo_Nao_SAV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Motivo_EEMI_SAV_NAO_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                            .addComponent(Label_SAV_Nao_Gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(SAV_Nao_Gravar_S, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SAV_Nao_Gravar_Nao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(EEMI_SAV_NAO_VOLTAR, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDesktopPanePCR1Layout.setVerticalGroup(
            jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePCR1Layout.createSequentialGroup()
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Motivo_Nao_SAV)
                    .addComponent(Motivo_EEMI_SAV_NAO_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPanePCR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAV_Nao_Gravar_S)
                    .addComponent(Label_SAV_Nao_Gravar)
                    .addComponent(SAV_Nao_Gravar_Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EEMI_SAV_NAO_VOLTAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Motivo_EEMI_SAV_NAO_Box.getAccessibleContext().setAccessibleName("Motivo_EEMI_SAV_NAO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jDesktopPanePCR1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPanePCR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupComboBox() {
        Motivo_EEMI_SAV_NAO_Box.addItem("-");
    
    List<Motivo_EEMI_SAV_NAO> motivos_EEMI_SAV_NAO = Motivo_EEMI_SAV_NAO.getAllMotivos_EEMI_SAV_NAO();
        for (Motivo_EEMI_SAV_NAO motivo_EEMI_SAV_NAO : motivos_EEMI_SAV_NAO) {
            Motivo_EEMI_SAV_NAO_Box.addItem(motivo_EEMI_SAV_NAO.getMOTIVO_EEMI_SAV_NAO());
        }
    }
    
    private void setupOptions() {
     
    }
    
    
    
    private void Motivo_EEMI_SAV_NAO_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motivo_EEMI_SAV_NAO_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Motivo_EEMI_SAV_NAO_BoxActionPerformed

    private void SAV_Nao_Gravar_NaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAV_Nao_Gravar_NaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAV_Nao_Gravar_NaoActionPerformed

    private void SAV_Nao_Gravar_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAV_Nao_Gravar_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAV_Nao_Gravar_SActionPerformed

    private void EEMI_SAV_NAO_VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EEMI_SAV_NAO_VOLTARActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EEMI_SAV_NAO_VOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_EEMI_SAV_NAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_EEMI_SAV_NAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_EEMI_SAV_NAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_EEMI_SAV_NAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_EEMI_SAV_NAO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EEMI_SAV_NAO_VOLTAR;
    private javax.swing.JLabel Label_Motivo_Nao_SAV;
    private javax.swing.JLabel Label_SAV_Nao_Gravar;
    private javax.swing.JComboBox<String> Motivo_EEMI_SAV_NAO_Box;
    private javax.swing.JButton SAV_Nao_Gravar_Nao;
    private javax.swing.JButton SAV_Nao_Gravar_S;
    private javax.swing.JDesktopPane jDesktopPanePCR1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
